import { duotone } from "@fortawesome/fontawesome-svg-core/import.macro";

export interface ExperienceInterface {
  readonly kind: string,
  readonly grade ?: string,
  readonly info ?: string,
  readonly job ?: string,
  readonly company ?: string,
  readonly color: string,
  readonly icon: string,
  readonly start: Date,
  readonly end: Date,
}

export const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

export const EXPERIENCES = [{
  kind: 'grade',
  grade: 'Bac IST EE',
  info: 'Industrial Sciences and Techniques - Electronic Engineering option',
  icon: duotone('graduation-cap'),
  color: '#f44336',
  start: new Date(2008, 9),
  end: new Date(2010, 6),
}, {
  kind: 'job',
  job: 'Versatile employee',
  company: 'Mac Donald\'s',
  icon: duotone('flask'),
  color: '#9c27b0',
  start: new Date(2010, 7),
  end: new Date(2010, 8),
}, {
  kind: 'grade',
  grade: 'BTS IRIS',
  info: 'IT and Network for Industries and Technical Services',
  icon: duotone('graduation-cap'),
  color: '#3f51b5',
  start: new Date(2010, 9),
  end: new Date(2012, 6),
}, {
  kind: 'job',
  job: 'Web developer',
  company: 'Mairie de Villieu-Loyes-Mollon',
  icon: duotone('flask'),
  color: '#2196f3',
  start: new Date(2011, 7),
  end: new Date(2011, 7),
}, {
  kind: 'job',
  job: 'Versatile employee',
  company: 'Vente privée',
  icon: duotone('flask'),
  color: '#009688',
  start: new Date(2012, 8),
  end: new Date(2012, 8),
}, {
  kind: 'both',
  grade: 'LP IEM',
  info: 'Embedded and Mobile Computing',
  job: 'Web & mobile developer',
  company: 'Urban Link / Meden Agan',
  icon: duotone('star-half'),
  color: '#4caf50',
  start: new Date(2012, 9),
  end: new Date(2013, 9),
}, {
  kind: 'grade',
  grade: 'Web development',
  info: 'Self-taught learning',
  icon: duotone('graduation-cap'),
  color: '#cddc39',
  start: new Date(2013, 10),
  end: new Date(2014, 3),
}, {
  kind: 'job',
  job: 'Web developer',
  company: 'Wanadev',
  icon: duotone('flask'),
  color: '#ffc107',
  start: new Date(2014, 4),
  end: new Date(2018, 10),
}, {
  kind: 'job',
  job: 'Web developer',
  company: 'AMTSolutions',
  icon: duotone('flask'),
  color: '#ff5722',
  start: new Date(2018, 11),
  end: new Date(),
}];
