export interface Store {
    height: number,
    width: number,
    color: string,
    tool: string,
    history: [],
    frame_idx: number,
    frame: (string|undefined)[][],
    layer_idx: number,
    layer: (string|undefined)[],
    palette: string[],
    data: (string|undefined)[][][],

    setHeight?: (height: number) => void,
    setWidth?: (width: number) => void,
    setColor?: (color: string) => void,
    setTool?: (tool: string) => void,
    setFrame?: (frame_idx: number) => void,
    setLayer?: (layer_idx: number) => void,
    setHistory?: (history: []) => void,
    setPalette?: (palette: string[]) => void,
    setData?: (data: (string|undefined)[][][]) => void,
}
